# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
#     - name: Restore gradle.properties
#       env:
#         USER: ${{ secrets.USER }}
#         USER_TOKEN: ${{ secrets.USER_TOKEN }}
#       shell: bash
#       run: |
#         mkdir -p ~/.gradle/
#         echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
#         echo ${USER} > ~/.gradle/gradle.properties
#         echo ${USER_TOKEN} > ~/.gradle/gradle.properties
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish with Gradle
      run: |
        ./gradlew publish -PUSER=${{ secrets.USER }} -PUSER_TOKEN=${{ secrets.USER_TOKEN }}
      env:
        USER: ${{ secrets.USER }}
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
